spring.application.name=Banco-CRUD

spring.datasource.url=jdbc:h2:mem:banco;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
# Show Hibernate SQL if you want
#spring.jpa.show-sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.org.springframework.beans.factory.support.DisposableBeanAdapter=ERROR
# Optional: H2 Web Console (great for debugging)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console